CREATE SCHEMA IF NOT EXISTS session;

CREATE TABLE session.users (
    id BIGINT PRIMARY KEY
);

CREATE TABLE session.wallets (
    user_id BIGINT PRIMARY KEY REFERENCES session.users (id),
    balance NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

CREATE TABLE session.charging_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES session.users (id),
    connector_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'COMPLETED')),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    energy_kwh NUMERIC(19, 6),
    cost NUMERIC(19, 2),
    tariff_price_per_kwh NUMERIC(19, 6) NOT NULL,
    tariff_start_fee NUMERIC(19, 6) NOT NULL,
    tariff_currency VARCHAR(3) NOT NULL
);

CREATE INDEX charging_sessions_user_id_idx ON session.charging_sessions (user_id);

