apiVersion: v1
kind: Service
metadata:
  name: session-service
  labels:
    app.kubernetes.io/name: session-service
    app.kubernetes.io/part-of: chargesquare
spec:
  selector:
    app.kubernetes.io/name: session-service
  ports:
    - name: http
      port: 8082
      targetPort: http
