spring:
  application:
    name: session-service
  datasource:
    url: ${SESSION_DB_URL}
    username: ${SESSION_DB_USERNAME}
    password: ${SESSION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: ${SESSION_DB_SCHEMA:session}
    default-schema: ${SESSION_DB_SCHEMA:session}
    create-schemas: true
    placeholders:
      session_schema: ${SESSION_DB_SCHEMA:session}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SESSION_DB_SCHEMA:session}
    open-in-view: false

station-service:
  base-url: ${STATION_SERVICE_URL:http://localhost:8081}

server:
  port: ${SESSION_SERVICE_PORT:8082}

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
